version: "3.8"

services:
  fastapi:
    build: ./fastapi_server
    container_name: fastapi-car-damage
    ports:
      - "10000:10000"
    volumes:
      - ./fastapi_server:/app

  streamlit:
    build: ./StreamLit_App
    container_name: streamlit-ui
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - ./StreamLit_App:/app
